const dateNow = new Date().toISOString();

export const DEFAULT_VAULT_ITEMS = [
	{
		id: 'demo-item-1',
		userId: 'demo-user-1',
		type: 'login',
		name: 'GitHub',
		username: 'demo+github@example.com',
		password: 'fk4uXg5i7dSz&!',
		uri: 'https://github.com',
		isFavourite: true,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-2',
		userId: 'demo-user-1',
		type: 'login',
		name: 'X',
		username: 'demo+twitter@example.com',
		password: 'W8z$1vLm#tQe',
		uri: 'https://x.com',
		isFavourite: false,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-3',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Facebook',
		username: 'demo+facebook@example.com',
		password: 'Xy93!vP$Ko2b',
		uri: 'https://facebook.com',
		isFavourite: false,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-4',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Netflix',
		username: 'demo+netflix@example.com',
		password: 'zT7!nQr#6pLs',
		uri: 'https://netflix.com',
		isFavourite: true,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-5',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Spotify',
		username: 'demo+spotify@example.com',
		password: 'hB2@xNc8$wQz',
		uri: 'https://spotify.com',
		isFavourite: false,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-6',
		userId: 'demo-user-1',
		type: 'login',
		name: 'LinkedIn',
		username: 'demo+linkedin@example.com',
		password: 'Lu4#tV1p@jHs',
		uri: 'https://linkedin.com',
		isFavourite: false,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-7',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Reddit',
		username: 'demo+reddit@example.com',
		password: 'Yt5$kLm!8rTx',
		uri: 'https://reddit.com',
		isFavourite: true,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-8',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Dropbox',
		username: 'demo+dropbox@example.com',
		password: 'Zq1!vBn#2xLp',
		uri: 'https://dropbox.com',
		isFavourite: false,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-9',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Trello',
		username: 'demo+trello@example.com',
		password: 'Jk7@xW3!pLm2',
		uri: 'https://trello.com',
		isFavourite: true,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-10',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Notion',
		username: 'demo+notion@example.com',
		password: 'Qe9#tY2!vMx1',
		uri: 'https://notion.so',
		isFavourite: false,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-11',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Amazon',
		username: 'demo+amazon@example.com',
		password: 'Sd8!kLp#7zXw',
		uri: 'https://amazon.com',
		isFavourite: false,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-12',
		userId: 'demo-user-1',
		type: 'login',
		name: 'eBay',
		username: 'demo+ebay@example.com',
		password: 'Vb5@pQr!3nZx',
		uri: 'https://ebay.com',
		isFavourite: false,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-13',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Zoom',
		username: 'demo+zoom@example.com',
		password: 'Rm6!vTq#2bNp',
		uri: 'https://zoom.us',
		isFavourite: true,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-14',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Slack',
		username: 'demo+slack@example.com',
		password: 'Uf2#xLp!5sKz',
		uri: 'https://slack.com',
		isFavourite: true,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-15',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Figma',
		username: 'demo+figma@example.com',
		password: 'Xj9!tQw#4vLp',
		uri: 'https://figma.com',
		isFavourite: false,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-16',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Canva',
		username: 'demo+canva@example.com',
		password: 'Ba7$yLk!1pQz',
		uri: 'https://canva.com',
		isFavourite: false,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-17',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Heroku',
		username: 'demo+heroku@example.com',
		password: 'Tm3!kXw#9lZp',
		uri: 'https://heroku.com',
		isFavourite: true,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-18',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Stripe',
		username: 'demo+stripe@example.com',
		password: 'Fz8@qLp!6nVs',
		uri: 'https://stripe.com',
		isFavourite: false,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-19',
		userId: 'demo-user-1',
		type: 'login',
		name: 'DigitalOcean',
		username: 'demo+do@example.com',
		password: 'Gy1!tZx#7vQw',
		uri: 'https://digitalocean.com',
		isFavourite: false,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-20',
		userId: 'demo-user-1',
		type: 'login',
		name: 'BBC iPlayer',
		username: 'demo@example.com',
		password: 'Kp5#xVn!2bMz',
		uri: 'https://www.bbc.co.uk/iplayer',
		isFavourite: true,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-21',
		userId: 'demo-user-1',
		type: 'login',
		name: 'PayPal',
		username: 'demo+paypal@example.com',
		password: 'Wf4!kLp#8zQs',
		uri: 'https://paypal.com',
		isFavourite: false,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-22',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Adobe',
		username: 'demo+example2@example.com',
		password: 'Nq6!bVt#3xLp',
		uri: 'https://adobe.com',
		isFavourite: true,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-23',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Airbnb',
		username: 'demo+example3@example.com',
		password: 'Uz8#pLk!5sQw',
		uri: 'https://airbnb.com',
		isFavourite: false,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-24',
		userId: 'demo-user-1',
		type: 'login',
		name: 'StackOverflow',
		username: 'demo+example4@example.com',
		password: 'Jd2!xQw#9vLp',
		uri: 'https://stackoverflow.com',
		isFavourite: true,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-25',
		userId: 'demo-user-1',
		type: 'login',
		name: 'YouTube',
		username: 'demo+example5@example.com',
		password: 'Rc7!kLp#1zXt',
		uri: 'https://youtube.com',
		isFavourite: false,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-26',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Instagram',
		username: 'demo+example6@example.com',
		password: 'Mb4#nLp!7vQz',
		uri: 'https://instagram.com',
		isFavourite: false,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-27',
		userId: 'demo-user-1',
		type: 'login',
		name: 'TikTok',
		username: 'demo+example7@example.com',
		password: 'Yk9@qLp!2xZw',
		uri: 'https://tiktok.com',
		isFavourite: true,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-28',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Uber',
		username: 'demo+example8@example.com',
		password: 'Tp8!vQw#6zLp',
		uri: 'https://uber.com',
		isFavourite: false,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-29',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Discord',
		username: 'demo+example9@example.com',
		password: 'Zn3#kLp!4xQs',
		uri: 'https://discord.com',
		isFavourite: true,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-30',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Twitch',
		username: 'demo+example10@example.com',
		password: 'Vf1!xQw#7bLp',
		uri: 'https://twitch.tv',
		isFavourite: false,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-31',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Duolingo',
		username: 'demo+example11@example.com',
		password: 'Qx5!vLp#2kZt',
		uri: 'https://duolingo.com',
		isFavourite: true,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-32',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Coursera',
		username: 'demo+example12@example.com',
		password: 'Hn7#kLp!9sQw',
		uri: 'https://coursera.org',
		isFavourite: false,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-33',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Khan Academy',
		username: 'demo+example13@example.com',
		password: 'Lb3!xQw#8vTp',
		uri: 'https://khanacademy.org',
		isFavourite: true,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-34',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Asana',
		username: 'demo+example14@example.com',
		password: 'Sr6!vLp#1kQz',
		uri: 'https://asana.com',
		isFavourite: false,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-36',
		userId: 'demo-user-1',
		type: 'login',
		name: 'ZoomInfo',
		username: 'demo+example16@example.com',
		password: 'Px8!vQw#4lKs',
		uri: 'https://zoominfo.com',
		isFavourite: false,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-37',
		userId: 'demo-user-1',
		type: 'login',
		name: 'HubSpot',
		username: 'demo+example17@example.com',
		password: 'Vn9!kLp#3xQw',
		uri: 'https://hubspot.com',
		isFavourite: false,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-38',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Bitbucket',
		username: 'demo+example18@example.com',
		password: 'Jf5#zLp!7vQx',
		uri: 'https://bitbucket.org',
		isFavourite: true,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-39',
		userId: 'demo-user-1',
		type: 'login',
		name: 'Pinterest',
		username: 'demo+example19@example.com',
		password: 'Kz1!xQw#6bLp',
		uri: 'https://pinterest.com',
		isFavourite: false,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
	{
		id: 'demo-item-40',
		userId: 'demo-user-1',
		type: 'login',
		name: 'ITVX',
		username: 'test@example.com',
		password: 'Kz1!xQw#6bLp',
		uri: 'https://itv.com',
		isFavourite: false,
		folderId: null,
		createdAt: dateNow,
		updatedAt: dateNow,
	},
];
