type ItemType = 'login' | 'card' | 'identity' | 'note' | 'key';

interface VaultItem {
	type: ItemType;
	name: string;
	username: string;
	password: string;
	uri: string;
	folder?: string | null;
}

const vaultItems: VaultItem[] = [
	{
		type: 'login',
		name: 'Gmail',
		username: 'john.doe@gmail.com',
		password: 'nR3!pLq9xB2v',
		uri: 'https://mail.google.com',
		folder: null,
	},
	{
		type: 'login',
		name: 'Facebook',
		username: 'jane.doe@example.com',
		password: 'Fb!2024login*',
		uri: 'https://www.facebook.com',
		folder: null,
	},
	{
		type: 'login',
		name: 'Twitter',
		username: 'socialguy123',
		password: 'Twt@#78Zq!',
		uri: 'https://twitter.com',
		folder: 'Social',
	},
	{
		type: 'login',
		name: 'Amazon',
		username: 'shopaholic@example.com',
		password: 'Amaz0n!Prime44',
		uri: 'https://www.amazon.com',
		folder: 'Shopping',
	},
	{
		type: 'login',
		name: 'LinkedIn',
		username: 'professional.me@workmail.com',
		password: 'Lnkd!nSecure88',
		uri: 'https://www.linkedin.com',
		folder: 'Work',
	},
	{
		type: 'login',
		name: 'Netflix',
		username: 'netflix_user2024@example.com',
		password: 'WatchIt#Now@12',
		uri: 'https://www.netflix.com',
		folder: 'Entertainment',
	},
	{
		type: 'login',
		name: 'Spotify',
		username: 'musicfan@example.com',
		password: 'Str3amL0ud%2024',
		uri: 'https://www.spotify.com',
		folder: 'Entertainment',
	},
	{
		type: 'login',
		name: 'Instagram',
		username: 'photoqueen93',
		password: 'Insta#Secure44!',
		uri: 'https://www.instagram.com',
		folder: 'Social',
	},
	{
		type: 'login',
		name: 'Reddit',
		username: 'memeuser99',
		password: 'r3ddit!!L0g1n',
		uri: 'https://www.reddit.com',
		folder: 'Social',
	},
	{
		type: 'login',
		name: 'eBay',
		username: 'seller123@example.com',
		password: 'eBay@S3ller2024',
		uri: 'https://www.ebay.com',
		folder: 'Shopping',
	},
	{
		type: 'login',
		name: 'Dropbox',
		username: 'backupdrive@example.com',
		password: 'Dr0pMyStuff!',
		uri: 'https://www.dropbox.com',
		folder: 'Cloud',
	},
	{
		type: 'login',
		name: 'GitHub',
		username: 'coderpro',
		password: 'C0d3r!GH@hub',
		uri: 'https://github.com',
		folder: 'Development',
	},
	{
		type: 'login',
		name: 'Stack Overflow',
		username: 'overflowfan123',
		password: 'St@ckOv#help!',
		uri: 'https://stackoverflow.com',
		folder: 'Development',
	},
	{
		type: 'login',
		name: 'Notion',
		username: 'notes@example.com',
		password: 'N0tionRulez!!',
		uri: 'https://www.notion.so',
		folder: 'Productivity',
	},
	{
		type: 'login',
		name: 'Trello',
		username: 'teamlead@example.com',
		password: 'Trello#Plan88',
		uri: 'https://trello.com',
		folder: 'Work',
	},
	{
		type: 'login',
		name: 'Zoom',
		username: 'calls@example.com',
		password: 'Z00mT1me!',
		uri: 'https://zoom.us',
		folder: 'Work',
	},
	{
		type: 'login',
		name: 'Slack',
		username: 'workspace@example.com',
		password: 'Sl@ckPass!2024',
		uri: 'https://slack.com',
		folder: 'Work',
	},
	{
		type: 'login',
		name: 'Microsoft',
		username: 'msuser@outlook.com',
		password: 'Micr0s0ft123!',
		uri: 'https://account.microsoft.com',
		folder: 'Work',
	},
	{
		type: 'login',
		name: 'Apple',
		username: 'appleuser@icloud.com',
		password: 'iCloudMe2024$',
		uri: 'https://appleid.apple.com',
		folder: 'Personal',
	},
	{
		type: 'login',
		name: 'Pinterest',
		username: 'pinterestfan@example.com',
		password: 'Pins&Boards88',
		uri: 'https://www.pinterest.com',
		folder: 'Social',
	},
	{
		type: 'login',
		name: 'Coursera',
		username: 'learnfast@example.com',
		password: 'Edu@1234Learn!',
		uri: 'https://www.coursera.org',
		folder: 'Education',
	},
	{
		type: 'login',
		name: 'Udemy',
		username: 'devstudent@example.com',
		password: 'Udemy$Best2024',
		uri: 'https://www.udemy.com',
		folder: 'Education',
	},
	{
		type: 'login',
		name: 'Khan Academy',
		username: 'khanteacher@example.com',
		password: 'KhanPower!!88',
		uri: 'https://www.khanacademy.org',
		folder: 'Education',
	},
	{
		type: 'login',
		name: 'Duolingo',
		username: 'languagebuff@example.com',
		password: 'Duo#Spanish88!',
		uri: 'https://www.duolingo.com',
		folder: 'Education',
	},
	{
		type: 'login',
		name: 'BBC',
		username: 'newsreader@example.com',
		password: 'BBC4News@2024',
		uri: 'https://account.bbc.com',
		folder: 'News',
	},
	{
		type: 'login',
		name: 'NYTimes',
		username: 'reader@example.com',
		password: 'NYT@Sub2024!',
		uri: 'https://www.nytimes.com',
		folder: 'News',
	},
	{
		type: 'login',
		name: 'Twitch',
		username: 'gamer123',
		password: 'Tw!tchPl@y44',
		uri: 'https://www.twitch.tv',
		folder: 'Entertainment',
	},
	{
		type: 'login',
		name: 'Hulu',
		username: 'bingewatcher@example.com',
		password: 'HuLuTime123$',
		uri: 'https://www.hulu.com',
		folder: 'Entertainment',
	},
	{
		type: 'login',
		name: 'Disney+',
		username: 'disneyfan@example.com',
		password: 'Mickey&Friends22',
		uri: 'https://www.disneyplus.com',
		folder: 'Entertainment',
	},
	{
		type: 'login',
		name: 'Canva',
		username: 'designer@example.com',
		password: 'Canv@Create#2024',
		uri: 'https://www.canva.com',
		folder: 'Design',
	},
	{
		type: 'login',
		name: 'Figma',
		username: 'figuser@example.com',
		password: 'F1gm@Secure$',
		uri: 'https://www.figma.com',
		folder: 'Design',
	},
	{
		type: 'login',
		name: 'Behance',
		username: 'portfolio@example.com',
		password: 'Beh4nce@Work!',
		uri: 'https://www.behance.net',
		folder: 'Design',
	},
	{
		type: 'login',
		name: 'Dribbble',
		username: 'uidev@example.com',
		password: 'Dr!bb$Dev2024',
		uri: 'https://dribbble.com',
		folder: 'Design',
	},
	{
		type: 'login',
		name: 'PayPal',
		username: 'money@example.com',
		password: 'P@yMeNow!!22',
		uri: 'https://www.paypal.com',
		folder: 'Finance',
	},
	{
		type: 'login',
		name: 'Revolut',
		username: 'banking@example.com',
		password: 'Revolut$afe99',
		uri: 'https://www.revolut.com',
		folder: 'Finance',
	},
	{
		type: 'login',
		name: 'Wise',
		username: 'transfers@example.com',
		password: 'WiseMove#2024',
		uri: 'https://wise.com',
		folder: 'Finance',
	},
	{
		type: 'login',
		name: 'Binance',
		username: 'crypto@example.com',
		password: 'B!nanceCrYpt0',
		uri: 'https://www.binance.com',
		folder: 'Finance',
	},
	{
		type: 'login',
		name: 'Coinbase',
		username: 'btcuser@example.com',
		password: 'C0inBase!Trade$',
		uri: 'https://www.coinbase.com',
		folder: 'Finance',
	},
	{
		type: 'login',
		name: 'Bitwarden',
		username: 'vaultuser@example.com',
		password: 'MyVault@Secure',
		uri: 'https://vault.bitwarden.com',
		folder: 'Security',
	},
	{
		type: 'login',
		name: '1Password',
		username: 'safe@example.com',
		password: 'On3PassVault!',
		uri: 'https://my.1password.com',
		folder: 'Security',
	},
	{
		type: 'login',
		name: 'ProtonMail',
		username: 'securemail@example.com',
		password: 'Pr0ton$Email2024',
		uri: 'https://mail.proton.me',
		folder: 'Security',
	},
	{
		type: 'login',
		name: 'Signal',
		username: 'privchat@example.com',
		password: 'S!gnal4Me!!',
		uri: 'https://signal.org',
		folder: 'Communication',
	},
	{
		type: 'login',
		name: 'Telegram',
		username: 'chatuser123',
		password: 'T3l3gramChat44!',
		uri: 'https://web.telegram.org',
		folder: 'Communication',
	},
	{
		type: 'login',
		name: 'WhatsApp',
		username: 'wauser@example.com',
		password: 'W@ppSecure123',
		uri: 'https://web.whatsapp.com',
		folder: 'Communication',
	},
	{
		type: 'login',
		name: 'Yahoo',
		username: 'legacy@example.com',
		password: 'Yah00Login88!',
		uri: 'https://login.yahoo.com',
		folder: 'Personal',
	},
	{
		type: 'login',
		name: 'Zoho',
		username: 'bizmail@example.com',
		password: 'Z0h0@Inbox2024',
		uri: 'https://www.zoho.com',
		folder: 'Work',
	},
	{
		type: 'login',
		name: 'Outlook',
		username: 'outlookuser@example.com',
		password: 'Outlook@Office!',
		uri: 'https://outlook.live.com',
		folder: 'Work',
	},
	{
		type: 'login',
		name: 'Quora',
		username: 'askme@example.com',
		password: 'QuoraQ&A@44',
		uri: 'https://www.quora.com',
		folder: 'Social',
	},
];

export { vaultItems };
